# Channel: enrollchannel
apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricMainChannel
metadata:
  name: enrollchannel
  namespace: fabric-bevel
spec:
  name: enrollchannel
  # Admin organization for channel
  adminPeerOrganizations:
    mspID: AdminOrgMSP
  # Orderer reference
  ordererOrganizations:
    - mspID: OrdererOrgMSP
      caName: ca-orderer
      caNamespace: fabric-bevel
      orderers:
        - orderer0.fabric-bevel.svc.cluster.local:7050
  # Peer organizations participating in channel
  peerOrganizations:
    - mspID: AdminOrgMSP
      caName: ca-admin
      caNamespace: fabric-bevel
    - mspID: StudentOrgMSP
      caName: ca-student
      caNamespace: fabric-bevel
  # Channel configuration
  externalOrdererOrganizations: []
  channelConfig:
    policies:
      Admins:
        mod_policy: Admins
        type: ImplicitMeta
        rule: MAJORITY Admins
      Readers:
        mod_policy: Admins
        type: ImplicitMeta
        rule: ANY Readers
      Writers:
        mod_policy: Admins
        type: ImplicitMeta
        rule: ANY Writers
    capabilities:
      - V2_0
    application:
      capabilities:
        - V2_0
      policies:
        Admins:
          mod_policy: Admins
          type: ImplicitMeta
          rule: MAJORITY Admins
        Readers:
          mod_policy: Admins
          type: ImplicitMeta
          rule: ANY Readers
        Writers:
          mod_policy: Admins
          type: ImplicitMeta
          rule: ANY Writers
        Endorsement:
          mod_policy: Admins
          type: ImplicitMeta
          rule: MAJORITY Endorsement
        LifecycleEndorsement:
          mod_policy: Admins
          type: ImplicitMeta
          rule: MAJORITY Endorsement
    orderer:
      batchSize:
        maxMessageCount: 10
        absoluteMaxBytes: 103809024
        preferredMaxBytes: 524288
      batchTimeout: 2s
      capabilities:
        - V2_0
      etcdRaft:
        options:
          electionTick: 10
          heartbeatTick: 1
          maxInflightBlocks: 5
          snapshotIntervalSize: 16777216
          tickInterval: 500ms
      policies:
        Admins:
          mod_policy: Admins
          type: ImplicitMeta
          rule: MAJORITY Admins
        Readers:
          mod_policy: Admins
          type: ImplicitMeta
          rule: ANY Readers
        Writers:
          mod_policy: Admins
          type: ImplicitMeta
          rule: ANY Writers
        BlockValidation:
          mod_policy: Admins
          type: ImplicitMeta
          rule: ANY Writers
      ordererType: etcdraft
---
# Join AdminOrg Peer to channel
apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricFollowerChannel
metadata:
  name: follower-admin-enrollchannel
  namespace: fabric-bevel
spec:
  anchorPeers:
    - host: peer0-admin.fabric-bevel.svc.cluster.local
      port: 7051
  hlfIdentity:
    secretKey: user.yaml
    secretName: admin-admin-identity
    secretNamespace: fabric-bevel
  mspId: AdminOrgMSP
  name: enrollchannel
  orderers:
    - certificate: ""
      url: grpcs://orderer0.fabric-bevel.svc.cluster.local:7050
  peersToJoin:
    - name: peer0-admin
      namespace: fabric-bevel
  externalPeersToJoin: []
---
# Join StudentOrg Peer to channel
apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricFollowerChannel
metadata:
  name: follower-student-enrollchannel
  namespace: fabric-bevel
spec:
  anchorPeers:
    - host: peer0-student.fabric-bevel.svc.cluster.local
      port: 7051
  hlfIdentity:
    secretKey: user.yaml
    secretName: admin-student-identity
    secretNamespace: fabric-bevel
  mspId: StudentOrgMSP
  name: enrollchannel
  orderers:
    - certificate: ""
      url: grpcs://orderer0.fabric-bevel.svc.cluster.local:7050
  peersToJoin:
    - name: peer0-student
      namespace: fabric-bevel
  externalPeersToJoin: []
