apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-clean
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: master-1
  containers:
  - name: cuda-container
    image: nvidia/cuda:12.3.0-base-ubuntu22.04
    # Komutu direkt çalıştırmak yerine sleep atıyoruz ki çökmesin, içine girip biz bakacağız
    command: ["/bin/sh", "-c"]
    args: ["sleep 3600"]
    resources:
      limits:
        nvidia.com/gpu: 1
    env:
      # Sadece bizim temiz klasöre bak, sistem dosyalarına bulaşma
      - name: LD_LIBRARY_PATH
        value: "/nvidia-drivers"
    securityContext:
      privileged: true
    volumeMounts:
      # Binary'yi (komutu) al
      - name: nvidia-smi
        mountPath: /usr/bin/nvidia-smi
        readOnly: true
      # Temiz driver klasörünü al
      - name: clean-drivers
        mountPath: /nvidia-drivers
        readOnly: true
  volumes:
    - name: nvidia-smi
      hostPath:
        path: /usr/bin/nvidia-smi
    # Host üzerinde az önce oluşturduğumuz temiz klasör
    - name: clean-drivers
      hostPath:
        path: /opt/nvidia-drivers