apiVersion: v1
kind: Namespace
metadata:
  name: bitirme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitirme-backend
  namespace: bitirme
  labels:
    app: bitirme-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitirme-backend
  template:
    metadata:
      labels:
        app: bitirme-backend
    spec:
      imagePullSecrets:
        - name: gitlab-reg-cred
      containers:
        - name: bitirme-backend
          image: 172.28.6.240:32003/kerem-bitirme/images/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              protocol: TCP
          env:
            - name: PORT
              value: "8001"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: bitirme-secret
                  key: db-host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bitirme-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bitirme-secret
                  key: db-root-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: bitirme-secret
                  key: db-name
            - name: ACCESS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bitirme-secret
                  key: access-jwt-secret
            - name: REFRESH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bitirme-secret
                  key: refresh-jwt-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bitirme-backend
  namespace: bitirme
  labels:
    app: bitirme-backend
spec:
  type: ClusterIP
  selector:
    app: bitirme-backend
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
