apiVersion: v1
kind: Secret
metadata:
  name: bitirme-secret
  namespace: bitirme
  labels:
    app: bitirme
type: Opaque
stringData:
  db-root-password: "**********"
  db-host: "***********"
  db-user: "**************"
  db-name: "****************"
  access-jwt-secret: "****************"
  refresh-jwt-secret: "****************"
