# StudentOrg Peer0
apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricPeer
metadata:
  name: peer0-student
  namespace: fabric-bevel
spec:
  image: quay.io/kfsoftware/fabric-peer
  tag: amd64-2.5.0
  dockerSocketPath: "/var/run/docker.sock"
  mspID: StudentOrgMSP
  hosts:
    - peer0-student
    - peer0-student.fabric-bevel
    - peer0-student.fabric-bevel.svc.cluster.local
  externalEndpoint: ""
  external_chaincode_builder: true
  istio:
    port: 443
  service:
    type: ClusterIP
  storage:
    couchdb:
      accessMode: ReadWriteOnce
      storageClass: "local-path"
      size: "5Gi"
    peer:
      accessMode: ReadWriteOnce
      size: "5Gi"
      storageClass: "local-path"
    chaincode:
      accessMode: ReadWriteOnce
      size: "2Gi"
      storageClass: "local-path"
  couchdb:
    user: "couchdb"
    password: "couchdb"
  gossip:
    externalEndpoint: ""
    endpoint: ""
    bootstrap: ""
    orgLeader: false
    useLeaderElection: true
  discovery:
    period: "60s"
    touchPeriod: "60s"
  logging:
    level: info
    peer: info
    cauthdsl: warning
    gossip: info
    grpc: error
    ledger: info
    msp: info
    policies: warning
  resources:
    peer:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 1Gi
    couchdb:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "500m"
        memory: 512Mi
    chaincode:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: "500m"
        memory: 512Mi
  secret:
    enrollment:
      component:
        cahost: ca-student.fabric-bevel.svc.cluster.local
        caname: ca
        caport: 7054
        catls:
          cacert: ""
        enrollid: admin
        enrollsecret: adminpw
      tls:
        cahost: ca-student.fabric-bevel.svc.cluster.local
        caname: tlsca
        caport: 7054
        catls:
          cacert: ""
        csr:
          cn: "peer0-student"
          hosts:
            - "peer0-student"
            - "peer0-student.fabric-bevel.svc.cluster.local"
        enrollid: admin
        enrollsecret: adminpw
  stateDb: couchdb
