# Fabric Wallet Secret
# This secret should contain the identity credentials for connecting to Fabric
# You need to create this secret with your actual wallet files
#
# Example command to create this secret:
# kubectl create secret generic fabric-wallet \
#   --from-file=admin.id=./wallet/admin.id \
#   -n fabric-app
#
# Or use the template below and encode your credentials in base64
apiVersion: v1
kind: Secret
metadata:
  name: fabric-wallet
  namespace: fabric-app
type: Opaque
data:
  # Base64 encoded identity file
  # Replace with: cat wallet/admin.id | base64
  admin.id: |
    eyJ0eXBlIjoiWC41MDkiLCJ2ZXJzaW9uIjoxLCJtc3BJZCI6Ik9yZzFNU1AifQ==
