apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ca-orderer-org-lh
  namespace: fabric
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
